const LOAD_START = "LOAD_START"
const LOAD_SUCCESS = "LOAD_SUCCESS" 
const LOAD_FAILURE = "LOAD_FAILURE"
const SUBMIT_POST_LIST = "SUBMIT_POST_LIST"
const EDIT_POST = "EDIT_POST"
const DEL_POST = "DEL_POST"
const DEL_POST_SUCCESS = "DEL_POST_SUCCESS"
const SELECT_POST = "SELECT_POST"
const CREATE_POST_START = "CREATE_POST_START"
const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS"
const CREATE_POST_FAIL = "CREATE_POST_FAIL"
const ADD_POST_START = "ADD_POST_START"
const ADD_POST_SUCCESS = "ADD_POST_SUCCESS"
const ADD_POST_FAIL = "ADD_POST_FAIL"

export {LOAD_START, CREATE_POST_START, CREATE_POST_SUCCESS, CREATE_POST_FAIL, LOAD_SUCCESS, LOAD_FAILURE, SUBMIT_POST_LIST, EDIT_POST, DEL_POST, DEL_POST_SUCCESS, SELECT_POST,
    ADD_POST_FAIL, ADD_POST_START, ADD_POST_SUCCESS}